app/models.py
# -*- coding:utf-8 -*-  
from . import db
from datetime import datetime
from markdown import markdown
import bleach
class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(64))
    ctext = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index = True,default = datetime.utcnow)

    def __repr__(self):
        return '<User %r>' % self.ctext

class Essay(db.Model):
    __tablename__ = 'essays'

    id = db.Column(db.Integer,primary_key = True)
    tittle = db.Column(db.String(300),index=True)
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime,default=datetime.utcnow,index=True)
    kind_id = db.Column(db.Integer, db.ForeignKey('kinds.id'))
    body_html = db.Column(db.Text)

    def __repr__(self):
        return '<Essay %r>' % self.tittle

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                            'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                            'h1', 'h2', 'h3', 'p']
        target.body_html = bleach.linkify(bleach.clean(\
                markdown(value, output_format='html'),\
                tags=allowed_tags, strip=True))

db.event.listen(Essay.body, 'set', Essay.on_changed_body)



class Kind(db.Model):
    __tablename__ = 'kinds'

    id = db.Column(db.Integer, primary_key = True,index= True)
    name = db.Column(db.String(200))

    essays = db.relationship('Essay', backref='kind')

    def __repr__(self):
        return '<Kind %r >' % self.name

app/main/forms.py
# -*- coding:utf-8 -*-  
#存放表单
from flask.ext.wtf import Form
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import Required

class CommentFrom(Form):
    Name = StringField('Name',validators=[Required()])
    Text = TextAreaField('Comment',validators=[Required()])
    SubButton = SubmitField('Submit')

app/write/forms.py
# -*- coding:utf-8 -*-  
#存放表单
from flask.ext.wtf import Form
from wtforms import TextField, BooleanField, PasswordField, TextAreaField, validators,StringField,SubmitField,SelectField
from wtforms.validators import Required
from flask_pagedown.fields import PageDownField

class Compose(Form):
    tittle = StringField('tittle',validators=[Required()])
    body = PageDownField('Enter your idea', validators=[Required()])
    kind = SelectField('Colum',coerce=int,choices=[(1,u'Web开发'),(2,u'机器学习'),(3,u'用python娱乐'),(4,u'知乎的收获'),(5,u'随写')])
    sub = SubmitField('Submit')

class KindForm(Form):
    name = StringField('name')
    sub = SubmitField('Submit')

FaceMark/DateProcess/__init__.py
# the function of this model :(m the num of image, d the dimension of X)
    ## input:  the image'url and score
    ## output: [m*d]X Matrix and Y can directly use to gradient descent

FaceMark/__init__.py
import json
import numpy as np
from DateProcess import InDate
from Gradient import Gradient

def train(alpha,num_iters,train_set,x_file,y_file,theta_file):
    ## train function
    ## parameters is  path

    InDate.process(Inpath = train_set,Xpaht = x_file,Ypath = y_file)
    save(theta_file,Gradient.GradientDescent(X=InDate.load_date(x_file),y=InDate.load_date(y_file),alpha=alpha,num_iters=num_iters))

def mark(image_url,theta_file):
    theta = InDate.load_date(theta_file)
    X= InDate.get_Xlist(image_url)
    X = np.array(InDate.load_date('Date/test.json'))
    X.shape = (1,X.shape[0])
    l = Gradient.Normalization(InDate.load_date('Date/X.json'),InDate.load_date('Date/Y.json'))
    X = (X-l[2][0])/l[2][1]
    score = np.dot(X,theta)*l[3][1]+l[3][0]
    return score


def save(path,theta):
    with open(path,'w') as f:
        f.write(json.dumps(theta.tolist()))


print mark('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1489549067407&di=b8822dfa6849b5e32ae38ea01811519f&imgtype=0&src=http%3A%2F%2Fpic18.photophoto.cn%2F20110120%2F0036036748117379_b.jpg','Date/theta.json')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_pagedown import PageDown
from config import config
from config import config
from flask_pagedown import  PageDown

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
pagedown = PageDown()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)


    bootstrap.init_app(app)
    moment.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    pagedown.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    #from .auth import auth as auth_blueprint
    #app.register_blueprint(auth_blueprint)

    from .write import write as write_blueprint
    app.register_blueprint(write_blueprint,url_prefix = '/write')

    return app

app/facemark/views.py
from .. import db
from datetime import datetime
from flask import render_template,session,redirect,url_for
from . import facemark
from .forms import MarkComment
import InDate

@facemark.route('/mark',methods = ['GET','POST'])
def facemarking():
    id = InDate.getID()
    img_url = InDate.getItem()[id]['image_urls'][0]
    form = MarkComment()
    if form.validate_on_submit():
        InDate.setID(id+1)
        if form.score.data == 0 :
            return redirect(url_for("facemark.facemarking"))
        else:
            score = form.score.data
            InDate.outItem(id=id, url=img_url, score=score)
            return redirect(url_for("facemark.facemarking"))
    return  render_template("facemarking/index.html", img_url=img_url, form=form, id=id)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from .import views,errors

app/main/views.py
from datetime import datetime
from flask import render_template,session,redirect,url_for,request
from . import main
from .forms import*
from .. import *
from ..models import Comment,Essay
from ..auth.forms import CommentFrom

@main.route('/',methods = ['GET','POST'])
def index():
    return render_template("index.html")

@main.route('/Self',methods = ['GET','POST'])
def Self_introduction():
    page = request.args.get('page',1,type = int)
    form = CommentFrom()
    if form.validate_on_submit() :
        comment = Comment(name = form.Name.data,ctext = form.Text.data)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('main.Self_introduction'))
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(\
        page,per_page=10,error_out=False)
    comments = pagination.items

    return render_template("self.html", form = form, comments = comments, pagination = pagination)

@main.route('/Colum',methods = ['GET','POST'])
def In_Colum():
    colum = request.args.get('colum',type = int)
    essays = Essay.query.filter_by(kind_id=colum).all()
    return render_template("colum.html",essays = essays)

@main.route('/EssayList/<int:id>')
def In_Essay(id):
    essay = Essay.query.get_or_404(id)
    return render_template('essay.html',essay = essay)

app/write/__init__.py
from flask import Blueprint

write = Blueprint('write',__name__)

from .import views

app/write/views.py
from .. import db
from datetime import datetime
from flask import render_template,session,redirect,url_for
from ..models import Essay,Kind
from .forms import Compose,KindForm
from . import write


@write.route('/kind',methods = ['GET','POST'])
def Write_addKind():
    form = KindForm()

    if form.validate_on_submit() :
        kind = Kind(name = form.name.data)
        db.session.add(kind)
        db.session.commit()
        return redirect(url_for('write.addKind'))
    return render_template('write/kindadd.html',form = form)

@write.route('/',methods = ['GET','POST'])
def Write_compose():
    form = Compose()
    if form.validate_on_submit() :
        essay = Essay(tittle = form.tittle.data,body = form.body.data,kind_id = form.kind.data )
        db.session.add(essay)
        db.session.commit()
        return redirect(url_for('write.Write_compose'))
    return render_template('write/write.html',form = form)

app/templates/Self.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block head %}
{{ super() }}
<style type="text/css">
.contain{

    padding-top: 60px;
}

.List{
    padding-left: 400px;
    margin-top: -400px;
}
</style>
{% endblock %}

{% block page_content %}

<div class="contain" >
    <div class="myphoto">
    <img src="{{ url_for('static', filename='Image/myself.png') }}" height="250px" width="250px" class="img-circle">
    </div>
    <div class="intrduce">
    <h3>姓名：<small>苏畅</small> </h3>
    <h3>生日： <small>一九九七年七月三十一日</small></h3>
    <h3>现今： <small>北京林业大学-计算机类</small></h3>
    <h3>爱好：<small>写代码 机器学习</small></h3>
    </div>

</div>

<div class="List">
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="name"><h3>{{ comment.name }} :<small>{{ comment.ctext }}</small></h3></div>
    </li>
    {% endfor %}
</ul>
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.Self_introduction') }}
</div>
{{ wtf.quick_form(form=form) }}

</div>




{% endblock %}

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
             <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %} 

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}SuStaion{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                 data-target="#example-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">SuChang</a>
        </div>
                <div class="collapse navbar-collapse" id="example-navbar-collapse">
                  <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.Self_introduction') }}">自我介绍</a></li>
                    <li><a href="{{ url_for('main.In_Colum',colum = 1) }}">Web开发</a></li>
                    <li><a href="{{ url_for('main.In_Colum',colum = 2) }}">机器学习</a></li>
                    <li><a href="{{ url_for('main.In_Colum',colum = 3) }}">用Python娱乐</a></li>
                    <li><a href="{{ url_for('main.In_Colum',colum = 4) }}">知乎收获</a></li>
                    <li><a href="{{ url_for('main.In_Colum',colum = 5) }}">随写</a></li>
                  </ul>
                </div>       
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}
    <!-- 内容段 -->
    {% endblock %}
</div>
{% endblock %}

app/templates/colum.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block head %}
{{ super() }}
<style type="text/css">
.List{

}
</style>
{% endblock %}

{% block page_content %}
{% if essays %}
    <div class="List">
    {% for essay in essays %}
        <h3><small><span class="glyphicon glyphicon-chevron-right"></span></small>><a href="{{ url_for('main.In_Essay',id = essay.id) }}">{{ essay.tittle }}</a></h3>
    {% endfor %}
    </div>
{% else %}
<h1>None</h1>
{% endif %}

{% endblock %}

app/templates/comment/comment.html
{% extends "./base.html" %}



{% block page_content %}
<div class="List">
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="name"><h3>{{ comment.name }} :</h3></div>
        <div class="text"><p>{{ comment.ctext }}</p></div>
    </li>
    {% endfor %}
</ul>
</div>

<div class="form">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/essay.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block head %}
{{ super() }}
<style type="text/css">

</style>
{% endblock %}

{% block page_content %}
    <div class="tittle"><h1>{{ essay.tittle }} <small> {{ moment(essay.timestamp).format('LLL') }}</small></h1></div>
    <div class="conText">{{ essay.body_html|safe }}</div>
{% endblock %}

app/templates/facemarking/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<style type="text/css">
    .contain{
        padding-top: 60px;
    }
</style>
{% endblock %}

{% block page_content %}
<div class="contain" align="center">
<h1>Welcome To My Station</h1>
<img src="{{ url_for('static', filename='Image/myself.png') }}" height="250px" width="250px" class="img-circle">
<h2>There are something about coding</h2>
<a href="https://github.com/IcyCC/SuStation"><img src="{{ url_for('static', filename='Ico/github.ico') }}" height="40px" width="40px">MyGitHub</a>
&nbsp;&nbsp;&nbsp;
<a href=""><img src="{{ url_for('static', filename='Ico/qq.ico') }}" height="40px" width="40px">:1103232282</a>
&nbsp;&nbsp;&nbsp;
<a href=""><img src="{{ url_for('static', filename='Ico/gmail.ico') }}" height="40px" width="40px">Samm23333@gmail.com</a>
</div>

{% endblock %}

app/templates/self.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block head %}
{{ super() }}
<style type="text/css">
.contain{

    padding-top: 60px;
}

.List{
    width: 300px;
}
</style>
{% endblock %}

{% block page_content %}

<div class="contain" >
    <div class="myphoto">
    <img src="{{ url_for('static', filename='Image/myself.png') }}" height="250px" width="250px" class="img-circle">
    </div>
    <div class="intrduce">
    <h3>姓名：<small>苏畅</small> </h3>
    <h3>生日： <small>一九九七年七月三十一日</small></h3>
    <h3>现今： <small>北京林业大学-计算机类</small></h3>
    <h3>爱好：<small>写代码 机器学习</small></h3>
    </div>

</div>

<div class="List">
    <h3>留言板</h3>
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="name"><h3>{{ comment.name }} :<small>{{ comment.ctext }}</small></h3></div>
    </li>
    {% endfor %}
</ul>
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.Self_introduction') }}
</div>
{{ wtf.quick_form(form=form) }}

</div>


{% endblock %}

app/templates/write/kindadd.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<style type="text/css">

</style>
{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form=form) }}
{% endblock %}

app/templates/write/write.html
{% extends "base.html" %}
{% block head %}
{{ super() }}
<style type="text/css">

</style>
{% endblock %}
{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}


{% block page_content %}
    {{ wtf.quick_form(form=form) }}
{% endblock %}